version: 2
workflows:
  version: 2
  workflow:
    jobs:
      - install
      - tests:
          requires:
            - install
      - linter:
          requires:
            - tests
      - build:
          requires:
            - linter
      - deploy:
          requires:
            - build


jobs:
  install:
    docker:
      - image: circleci/node:dubnium-browsers
    steps:
      - checkout
      - restore_cache:
          key: yarn-packages-{{ checksum "yarn.lock" }}
      - run: yarn install
      - save_cache:
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - ./node_modules
  tests:
    docker:
      - image: circleci/node:dubnium-browsers
    steps:
      - checkout
      - restore_cache:
          key: yarn-packages-{{ checksum "yarn.lock" }}
      - run: yarn test
      - save_cache:
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - ./node_modules
  linter:
    docker:
      - image: circleci/node:dubnium-browsers
    steps:
      - checkout
      - restore_cache:
          key: yarn-packages-{{ checksum "yarn.lock" }}
      - run: yarn format:check
      - save_cache:
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - ./node_modules
  build:
    docker:
      - image: circleci/node:dubnium-browsers
    only:
      ref:
        - main
    steps:
      - checkout
      - restore_cache:
          key: yarn-packages-{{ checksum "yarn.lock" }}
      - run: yarn build
      - save_cache:
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - ./node_modules
  deploy:
    docker:
      - image: circleci/node:dubnium-browsers
    only:
      ref:
        - main
    steps:
      - checkout
      - restore_cache:
          key: yarn-packages-{{ checksum "yarn.lock" }}
      - run: curl -X POST -d {} ${hook}
      - save_cache:
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - ./node_modules
